### ISSUE TITLE
Bad example code

### ISSUE THREAD

**Issue by Perlover** [murakmii/nostr-mux#1]
Hello,

You create here a Promise object but it's not used

https://github.com/murakmii/nostr-mux/blob/main/README.md#L83

```
// Get events at once
new Promise(resolve => {
  const events = [];
```

**Comment by murakmii** [comment]
@Perlover
Thank you for issue! I fixed it: https://github.com/murakmii/nostr-mux/commit/1d88188a1a34432dd82d97769d39855f55ab8e30
